name: Build and Push Server Docker Image

on:
  release:
    types: [created]

jobs:
  build_and_push:
    if: startsWith(github.event.release.tag_name, 'server@')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # This step is now corrected to use valid syntax
      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG_NAME#server@}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Server Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/our-gymnastics-server:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/our-gymnastics-server:latest