# Name of your workflow
name: Build and Push Server Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - '.github/workflows/docker-publish-server.yml'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Server Image
        uses: docker/build-push-action@v4
        with:
          # Change 1: Use the monorepo root as the context
          context: .
          # Change 2: Specify the path to the Dockerfile
          file: ./server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/our-gymnastics-server:latest