name: Build and Push Client Docker Image

on:
  release:
    types: [created]

jobs:
  build_and_push:
    # Only run this job if the release tag starts with 'client@'
    if: startsWith(github.event.release.tag_name, 'client@')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG_NAME#client@}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Client Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/our-gymnastics-client:${{ steps.get_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/our-gymnastics-client:latest