name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  release-client:
    runs-on: ubuntu-latest
    # This job only runs if changes were made in the 'client' directory
    if: "contains(github.event.head_commit.message, 'feat(client)') || contains(github.event.head_commit.message, 'fix(client)')"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: '20' }
      - run: npm ci
      - run: npx semantic-release
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release-server:
    runs-on: ubuntu-latest
    # This job only runs if changes were made in the 'server' directory
    if: "contains(github.event.head_commit.message, 'feat(server)') || contains(github.event.head_commit.message, 'fix(server)')"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: '20' }
      - run: npm ci
      - run: npx semantic-release
        working-directory: ./server
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}