name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # New diagnostic step to see what's installed
      - name: Verify Installation
        run: ls -la ./node_modules/.bin

      # Updated command to run the local executable directly
      - name: Run semantic-release
        run: ./node_modules/.bin/semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}