name: Create Release

on:
  push:
    branches: [ "main" ]

jobs:
  release-client:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: '20' }
      - run: npm ci
      - run: npx semantic-release
        working-directory: ./client
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release-server:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v3
        with: { node-version: '20' }
      - run: npm ci
      - run: npx semantic-release
        working-directory: ./server
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}